config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :people
  root 'users#index'
  get '/generate_pdf/:id', to: 'users#download_pdf'
  get '/echo', to: 'users#echo'
  get '/test', to: 'users#test'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord     
    has_many :shipping_addresses, dependent: :destroy
    accepts_nested_attributes_for :shipping_addresses, allow_destroy: true
    
    validates :name, uniqueness: { case_sensitive: false }, presence: true
    validates :agreement, acceptance: { message: 'must be checked' }
    validates :email, confirmation: { case_sensitive: false },
    format: { with: /\A(.+)@(.+)\z/, message: " '%{value}' with invalid format"},
    uniqueness: { case_senstive: false }, length: { minimum: 4, maximum: 254 }
    validates :email_confirmation, presence: true
    
    before_create UserCallbacks.new
    before_validation :normalize_name, on: :create
    after_touch :log_when_association_got_hit
    after_create :send_email_to_author, if: :author_wants_emails?
    after_initialize do |user|
        puts "You have initialized an object!"
    end
    after_find do |user|
        puts "You have found an object!"
    end

    private
    def normalize_name
        self.name.downcase!
    end

    def log_when_association_got_hit
        puts "Association being hit"
    end

    def author_wants_emails?
        true
    end

    def send_email_to_author
        puts 'Email Sent'
    end

end

app/controllers/users_controller.rb
require 'prawn'
class UsersController < ApplicationController
  USERS = { "lifo" => "world" }
  before_action :authenticate
    def index
      @users = User.all
      respond_to do |format|
        format.html
        format.xml { render xml: @users }
        format.json {render json: @users }
      end
    end

    def show
      @user = User.find(params[:id])
    end

    def new
      @user = User.new
      2.times { @user.shipping_addresses.build } 
    end
    
    def create
      @user = User.create(user_params)
      session[:current_user_name] = @user.name
      if @user.save
        redirect_to users_path, notice: "You Have Successfully Created User With Shipping Address"
      else
        render 'new'
      end
    end

    def destroy
      @user = User.find(params[:id])
      @user.destroy
    end

    def download_pdf
      @user = User.find(params[:id])
      send_data generate_pdf(@user),
                filename: "#{@user.name}.pdf",
                type: "application/pdf"
    end

    def echo
      render plain: "The parameter 'foo' is set as #{params[:testing].as_json}"
    end

    def test
      logger =  Rails.logger
      sher = Sherlock.new(logger)
      puts "#{sher.investigate}"
      child = ChildClassOne.new
      child.just_print_child
      my_tome = Document.new('pablo', 'esco', 'Never mess with pablo esco bar')
      my_tome.on_load do | doc |
        puts "hey, I've been loaded!"
      end
      words = my_tome.each_word {|word| puts word}
      characters = my_tome.each_character {|content| puts content}
      enum = Enumerator.new( my_tome, :each_character )

      render plain: "#{words },#{characters},#{enum.count}"
    end

    private
      def user_params
        params.require(:user).permit( :name, :agreement, :email, :email_confirmation, shipping_addresses_attributes: [ :city, :country ] )
      end

      def authenticate
        authenticate_or_request_with_http_digest do |username|
          USERS[username]
        end
      end

      def generate_pdf(user)
        Prawn::Document.new do
          text user.name, align: :center
          text "Name: #{user.name}"
        end.render
      end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>
<% @users.each do |user| %>
    User Name: <%= user.name %>
    <% user.shipping_addresses.each do |ship| %>
        <p>
            City: <%= ship.city %>
        </p>
        <p>
            Country: <%= ship.country %>
        </p>
    <% end %>
<% end %>
<h1> Latest Added User Name </h1>
<%= session['current_user_name'] %> <br>
<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<tr>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</tr>
  <tr>
    <td>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </td>
    <td>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </td>
    <td>
      <%= f.label :email_confirmation %>
      <%= f.text_field :email_confirmation %>
    </td>
  </tr>
  <%= f.fields_for :shipping_addresses do |ship_form| %>
    <tr>
      <td>
        <%= ship_form.label :city %>
        <%= ship_form.text_field :city %>
      </td>
      <td>
        <%= ship_form.label :country %>
        <%= ship_form.text_field :country %>
      </td>
    </tr>
  <% end %>  

  <p>
    <%= f.label :agreement %>
    <%= f.check_box :agreement %> </br>
  </p>
  </tr>
  <%= f.submit  %>
<% end %>